import { CROP_IDS, type Crop, type CropId } from "@/types/crop";

export const CROPS: Crop[] = [
  {
    id: "maize",
    name: "Maíz",
    iconEmoji: "🌽",
    scientificName: "Zea mays",
    gddBaseC: 10,
    idealPrecipMm: { min: 500, max: 800 },
    heatStressC: 35,
    tagline: "Cereal de temporada cálida, tolerante al calor hasta cierto punto.",
  },
  {
    id: "bean",
    name: "Frijol",
    iconEmoji: "🫘",
    scientificName: "Phaseolus vulgaris",
    gddBaseC: 10,
    idealPrecipMm: { min: 350, max: 600 },
    heatStressC: 32,
    tagline: "Leguminosa básica para sistemas mixtos, sensible al exceso de calor en floración.",
  },
  {
    id: "coffee",
    name: "Café",
    iconEmoji: "☕",
    scientificName: "Coffea arabica",
    gddBaseC: 7,
    idealPrecipMm: { min: 1200, max: 2200 },
    heatStressC: 32,
    tagline: "Cultivo tropical de altura, sensible al calor nocturno y a lluvias erráticas.",
  },
  {
    id: "cacao",
    name: "Cacao",
    iconEmoji: "🍫",
    scientificName: "Theobroma cacao",
    gddBaseC: 18,
    idealPrecipMm: { min: 1500, max: 2500 },
    heatStressC: 34,
    tagline: "Cultivo tropical de sombra, muy sensible a sequías y golpes de calor.",
  },
  {
    id: "rice",
    name: "Arroz",
    iconEmoji: "🌾",
    scientificName: "Oryza sativa",
    gddBaseC: 10,
    idealPrecipMm: { min: 800, max: 1600 },
    heatStressC: 36,
    tagline: "Cereal de alta demanda hídrica, clave en zonas tropicales irrigadas.",
  },
  {
    id: "sugarcane",
    name: "Caña de Azúcar",
    iconEmoji: "🎋",
    scientificName: "Saccharum officinarum",
    gddBaseC: 12,
    idealPrecipMm: { min: 1000, max: 1800 },
    heatStressC: 38,
    tagline: "Cultivo perenne tropical con fuerte respuesta a agua y radiación.",
  },
  {
    id: "tomato",
    name: "Tomate",
    iconEmoji: "🍅",
    scientificName: "Solanum lycopersicum",
    gddBaseC: 10,
    idealPrecipMm: { min: 400, max: 800 },
    heatStressC: 34,
    tagline: "Hortaliza intensiva, sensible al calor durante floración y cuaje.",
  },
  {
    id: "potato",
    name: "Papa",
    iconEmoji: "🥔",
    scientificName: "Solanum tuberosum",
    gddBaseC: 7,
    idealPrecipMm: { min: 500, max: 900 },
    heatStressC: 30,
    tagline: "Tubérculo andino de clima fresco, vulnerable a noches cálidas.",
  },
  {
    id: "avocado",
    name: "Aguacate",
    iconEmoji: "🥑",
    scientificName: "Persea americana",
    gddBaseC: 10,
    idealPrecipMm: { min: 700, max: 1400 },
    heatStressC: 36,
    tagline: "Frutal subtropical de alto valor, sensible a estrés hídrico y calor extremo.",
  },
  {
    id: "chile",
    name: "Chile",
    iconEmoji: "🌶️",
    scientificName: "Capsicum annuum",
    gddBaseC: 10,
    idealPrecipMm: { min: 400, max: 700 },
    heatStressC: 35,
    tagline: "Hortaliza de clima cálido, muy sensible a estrés en floración.",
  },
  {
    id: "banana",
    name: "Banano",
    iconEmoji: "🍌",
    scientificName: "Musa acuminata",
    gddBaseC: 14,
    idealPrecipMm: { min: 1200, max: 2500 },
    heatStressC: 37,
    tagline: "Cultivo tropical permanente, dependiente de humedad estable.",
  },
  {
    id: "sorghum",
    name: "Sorgo",
    iconEmoji: "🌿",
    scientificName: "Sorghum bicolor",
    gddBaseC: 10,
    idealPrecipMm: { min: 300, max: 650 },
    heatStressC: 38,
    tagline: "Cereal rústico para zonas secas, útil frente a temporadas irregulares.",
  },
  {
    id: "cassava",
    name: "Yuca",
    iconEmoji: "🥕",
    scientificName: "Manihot esculenta",
    gddBaseC: 14,
    idealPrecipMm: { min: 700, max: 1500 },
    heatStressC: 37,
    tagline: "Raíz tropical resiliente, tolerante a sequía moderada.",
  },
  {
    id: "cardamom",
    name: "Cardamomo",
    iconEmoji: "🌱",
    scientificName: "Elettaria cardamomum",
    gddBaseC: 16,
    idealPrecipMm: { min: 1500, max: 3000 },
    heatStressC: 33,
    tagline: "Cultivo de sombra húmeda, sensible a déficit de lluvia y calor excesivo.",
  },
];

export const CROP_ID_SET = new Set<string>(CROP_IDS);

export function isCropId(id: string): id is CropId {
  return CROP_ID_SET.has(id);
}

export function getCrop(id: string): Crop | undefined {
  return CROPS.find((c) => c.id === id);
}
